version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bkfs-doc-class-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uceix341dmcm"
s3_prefix = "bkfs-doc-class-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DocumentClassFn=295040540869.dkr.ecr.us-east-1.amazonaws.com/bkfs-doc-class-repo"]
