AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bkfs-document-classification

  Sample SAM Template for bkfs-document-classification

Globals:
  Function:
    Timeout: 180
  Api:
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
Resources:
  DocumentClassFn:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 180
      MemorySize: 3048
      Environment:
        Variables:
          MODEL_BUCKET_NAME: bkfsmodel
          MODEL_FILE_NAME_KEY: mlSGDClassifier.joblib
      Events:
        Predict:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
    Metadata:
      DockerTag: python3.6-v1
      DockerContext: ./lambda_helper
      Dockerfile: Dockerfile


Outputs:
  PredictApi:
    Description: "API Gateway endpoint URL for Prod stage for DocumentClassFn"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  DocumentClassFn:
    Description: "DocumentClassFn Lambda Function ARN"
    Value: !GetAtt DocumentClassFn.Arn
  DocumentClassFnIamRole:
    Description: "Implicit IAM Role created for DocumentClassFn"
    Value: !GetAtt DocumentClassFnRole.Arn
